import Foundation

struct NativeScanResult {
    let categories: [CleanupCategory]
    let totalBytes: Int64
    let totalItems: Int
}

final class NativeCleanerService: @unchecked Sendable {
    private let fileManager = FileManager.default

    struct TargetSpec {
        let id: String
        let name: String
        let detail: String
        let relativePath: String
        let icon: String
        let excludedSubpaths: Set<String>

        init(id: String, name: String, detail: String, relativePath: String, icon: String, excludedSubpaths: Set<String> = []) {
            self.id = id
            self.name = name
            self.detail = detail
            self.relativePath = relativePath
            self.icon = icon
            self.excludedSubpaths = excludedSubpaths
        }
    }

    private let targets: [TargetSpec] = [
        TargetSpec(
            id: "xcode-data",
            name: "Xcode Derived Data",
            detail: "Rebuildable intermediate build products & symbol indexes",
            relativePath: "Library/Developer/Xcode/DerivedData",
            icon: "hammer"
        ),
        TargetSpec(
            id: "safari-cache",
            name: "Safari Cache",
            detail: "Rebuildable web browsing cache and site media",
            relativePath: "Library/Caches/com.apple.Safari",
            icon: "safari"
        ),
        TargetSpec(
            id: "chrome-cache",
            name: "Google Chrome Cache",
            detail: "Rebuildable Google Chrome HTTP disk cache",
            relativePath: "Library/Caches/Google/Chrome",
            icon: "globe"
        ),
        TargetSpec(
            id: "firefox-cache",
            name: "Firefox Cache",
            detail: "Rebuildable Mozilla Firefox web cache",
            relativePath: "Library/Caches/org.mozilla.firefox",
            icon: "flame"
        ),
        TargetSpec(
            id: "npm-cache",
            name: "npm & Node Cache",
            detail: "Cached Node package manager archives and tarballs",
            relativePath: ".npm",
            icon: "chevron.left.forwardslash.chevron.right"
        ),
        TargetSpec(
            id: "logs",
            name: "User App Logs",
            detail: "Stale crash logs and application diagnostics",
            relativePath: "Library/Logs",
            icon: "doc.text"
        ),
        TargetSpec(
            id: "application-cache",
            name: "Other App Caches",
            detail: "Temporary cache files generated by installed apps",
            relativePath: "Library/Caches",
            icon: "shippingbox",
            excludedSubpaths: ["com.apple.Safari", "Google", "org.mozilla.firefox", "com.apple.appstore"]
        )
    ]

    private func resolveURL(for relativePath: String) -> URL {
        FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(relativePath)
    }

    /// Calculate the real size and file count of a directory
    func calculateDirectoryMetrics(at url: URL, excluding: Set<String> = []) -> (bytes: Int64, count: Int) {
        var isDir: ObjCBool = false
        guard fileManager.fileExists(atPath: url.path, isDirectory: &isDir) else {
            return (0, 0)
        }

        if !isDir.boolValue {
            let size = Int64((try? url.resourceValues(forKeys: [.fileSizeKey]))?.fileSize ?? 0)
            return (size, 1)
        }

        var totalBytes: Int64 = 0
        var totalCount: Int = 0

        guard let enumerator = fileManager.enumerator(
            at: url,
            includingPropertiesForKeys: [.fileSizeKey, .isDirectoryKey, .isRegularFileKey],
            options: [.skipsPackageDescendants]
        ) else {
            return (0, 0)
        }

        for case let fileURL as URL in enumerator {
            // Check exclusions relative to parent directory
            if !excluding.isEmpty {
                let relative = fileURL.path.replacingOccurrences(of: url.path + "/", with: "")
                let topComponent = relative.split(separator: "/").first.map(String.init) ?? ""
                if excluding.contains(topComponent) {
                    enumerator.skipDescendants()
                    continue
                }
            }

            guard let resourceValues = try? fileURL.resourceValues(forKeys: [.fileSizeKey, .isRegularFileKey]) else {
                continue
            }
            if resourceValues.isRegularFile == true {
                totalBytes += Int64(resourceValues.fileSize ?? 0)
                totalCount += 1
            }
        }

        return (totalBytes, totalCount)
    }

    /// Scan all known targets and return populated categories with real disk sizes
    func scanAllTargets(onProgress: @escaping (String, String, Int) -> Void = { _, _, _ in }) async -> NativeScanResult {
        var categories: [CleanupCategory] = []
        var totalBytes: Int64 = 0
        var totalItems: Int = 0

        for target in targets {
            let url = resolveURL(for: target.relativePath)
            let displayPath = "~/" + target.relativePath
            onProgress(target.name, displayPath, totalItems)

            let (bytes, count) = calculateDirectoryMetrics(at: url, excluding: target.excludedSubpaths)
            totalBytes += bytes
            totalItems += count
            onProgress(target.name, displayPath, totalItems)

            let formattedCount = count > 0 ? NumberFormatter.localizedString(from: NSNumber(value: count), number: .decimal) : "0"

            let category = CleanupCategory(
                id: target.id,
                name: target.name,
                detail: target.detail,
                path: displayPath,
                items: formattedCount,
                sizeBytes: bytes,
                icon: target.icon,
                isSelected: bytes > 0
            )

            categories.append(category)
        }

        // Check Docker if installed (whether Mole is installed or not)
        if let dockerMetrics = await inspectDockerMetrics(), dockerMetrics.bytes > 0 || dockerMetrics.count > 0 {
            onProgress("Docker Daemon", "docker://localhost", totalItems)
            let formattedCount = dockerMetrics.count > 0 ? NumberFormatter.localizedString(from: NSNumber(value: dockerMetrics.count), number: .decimal) : "1"
            let dockerCategory = CleanupCategory(
                id: "docker-images",
                name: "Docker Dangling & Unused Images",
                detail: "Dangling layers (<none>:<none>) & builder cache",
                path: "Docker Daemon",
                items: formattedCount,
                sizeBytes: dockerMetrics.bytes,
                icon: "shippingbox.fill",
                isSelected: dockerMetrics.bytes > 0
            )
            categories.append(dockerCategory)
            totalBytes += dockerMetrics.bytes
            totalItems += dockerMetrics.count
        }

        return NativeScanResult(categories: categories, totalBytes: totalBytes, totalItems: totalItems)
    }

    /// Safely cleans contents inside a target directory or triggers Docker pruning without deleting parent folders
    func cleanCategory(_ category: CleanupCategory, onProgress: @escaping (String) -> Void) async -> Int64 {
        // Docker special category
        if category.id == "docker-images" {
            let beforeBytes = category.sizeBytes
            _ = await cleanDocker(onProgress: onProgress)
            let after = await inspectDockerMetrics()
            let freed = max(beforeBytes - (after?.bytes ?? 0), beforeBytes)
            return freed
        }

        guard let spec = targets.first(where: { $0.id == category.id }) else { return 0 }
        let url = resolveURL(for: spec.relativePath)

        var isDir: ObjCBool = false
        guard fileManager.fileExists(atPath: url.path, isDirectory: &isDir), isDir.boolValue else {
            return 0
        }

        guard let contents = try? fileManager.contentsOfDirectory(
            at: url,
            includingPropertiesForKeys: [.fileSizeKey],
            options: []
        ) else {
            return 0
        }

        var cleanedBytes: Int64 = 0

        for itemURL in contents {
            let itemName = itemURL.lastPathComponent
            // Skip hidden system files and any excluded subpaths
            if itemName.hasPrefix(".") && itemName != ".npm" { continue }
            if spec.excludedSubpaths.contains(itemName) { continue }

            onProgress("Removing \(category.name) · \(itemName)")

            // Calculate actual recursive size before deletion
            let (itemBytes, _) = calculateDirectoryMetrics(at: itemURL)

            do {
                try fileManager.removeItem(at: itemURL)
                cleanedBytes += itemBytes
            } catch {
                // If permission is denied or file is locked by a running process, continue safely
                continue
            }
        }

        return cleanedBytes
    }

    // MARK: - Docker Integration

    private var dockerExecutableURL: URL? {
        let candidates = [
            "/usr/local/bin/docker",
            "/opt/homebrew/bin/docker",
            "/usr/bin/docker",
            FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".docker/bin/docker").path
        ]
        if let found = candidates.first(where: { fileManager.isExecutableFile(atPath: $0) }) {
            return URL(fileURLWithPath: found)
        }
        return nil
    }

    private func runDockerCommand(arguments: [String], timeoutSeconds: Double = 3.0) async -> String? {
        guard let executableURL = dockerExecutableURL else { return nil }

        return await withCheckedContinuation { continuation in
            let process = Process()
            let pipe = Pipe()
            process.executableURL = executableURL
            process.arguments = arguments
            process.standardOutput = pipe
            process.standardError = FileHandle.nullDevice

            let timer = DispatchSource.makeTimerSource(queue: DispatchQueue.global())
            timer.schedule(deadline: .now() + timeoutSeconds)
            timer.setEventHandler {
                if process.isRunning {
                    process.terminate()
                }
                timer.cancel()
            }
            timer.resume()

            process.terminationHandler = { _ in
                timer.cancel()
                let data = pipe.fileHandleForReading.readDataToEndOfFile()
                continuation.resume(returning: String(data: data, encoding: .utf8))
            }

            do {
                try process.run()
            } catch {
                timer.cancel()
                continuation.resume(returning: nil)
            }
        }
    }

    func inspectDockerMetrics() async -> (bytes: Int64, count: Int, isAvailable: Bool)? {
        guard dockerExecutableURL != nil else { return nil }
        var rawOutput = await runDockerCommand(arguments: ["system", "df", "--format", "{{json .}}"])
        if rawOutput == nil {
            rawOutput = await runDockerCommand(arguments: ["system", "df", "--format", "json"])
        }
        guard let output = rawOutput else { return nil }

        var totalReclaimableBytes: Int64 = 0
        var totalReclaimableCount = 0

        for line in output.components(separatedBy: .newlines) {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, let data = trimmed.data(using: .utf8),
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                continue
            }

            let type = (json["Type"] as? String) ?? ""
            if type == "Images" || type == "Build Cache" {
                if let reclRaw = json["Reclaimable"] as? String {
                    let sizePart = reclRaw.components(separatedBy: "(").first?.trimmingCharacters(in: .whitespaces) ?? ""
                    let bytes = parseByteString(sizePart)
                    totalReclaimableBytes += bytes
                }
                if let totalCountStr = json["TotalCount"] as? String, let count = Int(totalCountStr) {
                    totalReclaimableCount += count
                }
            }
        }

        if let danglingOutput = await runDockerCommand(arguments: ["images", "-f", "dangling=true", "-q"]) {
            let danglingCount = danglingOutput.components(separatedBy: .newlines).filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }.count
            if danglingCount > 0 {
                totalReclaimableCount = max(totalReclaimableCount, danglingCount)
            }
        }

        guard totalReclaimableBytes > 0 || totalReclaimableCount > 0 else { return nil }
        return (totalReclaimableBytes, totalReclaimableCount, true)
    }

    func cleanDocker(onProgress: @escaping (String) -> Void) async -> Int64 {
        onProgress("Pruning dangling Docker images (<none>:<none>)…")
        _ = await runDockerCommand(arguments: ["image", "prune", "-f"], timeoutSeconds: 15.0)

        onProgress("Pruning dangling Docker build cache…")
        _ = await runDockerCommand(arguments: ["builder", "prune", "-f"], timeoutSeconds: 15.0)

        return 0
    }

    private func parseByteString(_ str: String) -> Int64 {
        let scanner = Scanner(string: str)
        guard let val = scanner.scanDouble() else { return 0 }
        let unit = str.replacingOccurrences(of: "\(val)", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .uppercased()

        let multiplier: Double
        if unit.hasPrefix("T") { multiplier = 1024 * 1024 * 1024 * 1024 }
        else if unit.hasPrefix("G") { multiplier = 1024 * 1024 * 1024 }
        else if unit.hasPrefix("M") { multiplier = 1024 * 1024 }
        else if unit.hasPrefix("K") { multiplier = 1024 }
        else { multiplier = 1 }

        return Int64(val * multiplier)
    }
}
