import Foundation

struct NativeScanResult {
    let categories: [CleanupCategory]
    let totalBytes: Int64
    let totalItems: Int
}

final class NativeCleanerService: @unchecked Sendable {
    private let fileManager = FileManager.default

    struct TargetSpec {
        let id: String
        let name: String
        let detail: String
        let relativePath: String
        let icon: String
    }

    private let targets: [TargetSpec] = [
        TargetSpec(
            id: "xcode-data",
            name: "Xcode Derived Data",
            detail: "Rebuildable intermediate build products & symbol indexes",
            relativePath: "Library/Developer/Xcode/DerivedData",
            icon: "hammer"
        ),
        TargetSpec(
            id: "application-cache",
            name: "User App Cache",
            detail: "Temporary cache files generated by installed apps",
            relativePath: "Library/Caches",
            icon: "shippingbox"
        ),
        TargetSpec(
            id: "logs",
            name: "User App Logs",
            detail: "Stale crash logs and application diagnostics",
            relativePath: "Library/Logs",
            icon: "doc.text"
        ),
        TargetSpec(
            id: "app-store-cache",
            name: "App Store Cache",
            detail: "Temporary asset caches and download buffers",
            relativePath: "Library/Caches/com.apple.appstore",
            icon: "bag"
        ),
        TargetSpec(
            id: "safari-cache",
            name: "Safari Cache",
            detail: "Rebuildable web browsing cache and site media",
            relativePath: "Library/Caches/com.apple.Safari",
            icon: "safari"
        ),
        TargetSpec(
            id: "chrome-cache",
            name: "Chrome Cache",
            detail: "Rebuildable Google Chrome HTTP disk cache",
            relativePath: "Library/Caches/Google/Chrome",
            icon: "globe"
        ),
        TargetSpec(
            id: "npm-cache",
            name: "npm Cache",
            detail: "Cached Node package manager archives and tarballs",
            relativePath: ".npm",
            icon: "chevron.left.forwardslash.chevron.right"
        )
    ]

    private func resolveURL(for relativePath: String) -> URL {
        FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(relativePath)
    }

    /// Calculate the real size and file count of a directory
    func calculateDirectoryMetrics(at url: URL) -> (bytes: Int64, count: Int) {
        var isDir: ObjCBool = false
        guard fileManager.fileExists(atPath: url.path, isDirectory: &isDir), isDir.boolValue else {
            return (0, 0)
        }

        var totalBytes: Int64 = 0
        var totalCount: Int = 0

        guard let enumerator = fileManager.enumerator(
            at: url,
            includingPropertiesForKeys: [.fileSizeKey, .isDirectoryKey, .isRegularFileKey],
            options: [.skipsPackageDescendants]
        ) else {
            return (0, 0)
        }

        for case let fileURL as URL in enumerator {
            guard let resourceValues = try? fileURL.resourceValues(forKeys: [.fileSizeKey, .isRegularFileKey]) else {
                continue
            }
            if resourceValues.isRegularFile == true {
                totalBytes += Int64(resourceValues.fileSize ?? 0)
                totalCount += 1
            }
        }

        return (totalBytes, totalCount)
    }

    /// Scan all known targets and return populated categories with real disk sizes
    func scanAllTargets(onProgress: @escaping (String, String) -> Void) async -> NativeScanResult {
        var categories: [CleanupCategory] = []
        var totalBytes: Int64 = 0
        var totalItems: Int = 0

        for target in targets {
            let url = resolveURL(for: target.relativePath)
            let displayPath = "~/" + target.relativePath
            onProgress(target.name, displayPath)

            let (bytes, count) = calculateDirectoryMetrics(at: url)

            let formattedCount = count > 0 ? NumberFormatter.localizedString(from: NSNumber(value: count), number: .decimal) : "0"

            let category = CleanupCategory(
                id: target.id,
                name: target.name,
                detail: target.detail,
                path: displayPath,
                items: formattedCount,
                sizeBytes: bytes,
                icon: target.icon,
                isSelected: bytes > 0
            )

            categories.append(category)
            totalBytes += bytes
            totalItems += count
        }

        return NativeScanResult(categories: categories, totalBytes: totalBytes, totalItems: totalItems)
    }

    /// Safely cleans contents inside a target directory without deleting the parent folder itself
    func cleanCategory(_ category: CleanupCategory, onProgress: @escaping (String) -> Void) async -> Int64 {
        guard let spec = targets.first(where: { $0.id == category.id }) else { return 0 }
        let url = resolveURL(for: spec.relativePath)

        var isDir: ObjCBool = false
        guard fileManager.fileExists(atPath: url.path, isDirectory: &isDir), isDir.boolValue else {
            return 0
        }

        guard let contents = try? fileManager.contentsOfDirectory(
            at: url,
            includingPropertiesForKeys: [.fileSizeKey],
            options: []
        ) else {
            return 0
        }

        var cleanedBytes: Int64 = 0

        for itemURL in contents {
            let itemName = itemURL.lastPathComponent
            // Safety guard: skip system protected folders
            if itemName.hasPrefix(".") && itemName != ".npm" { continue }

            onProgress("Removing \(category.name) · \(itemName)")

            // Get size before removing
            if let values = try? itemURL.resourceValues(forKeys: [.fileSizeKey]), let size = values.fileSize {
                cleanedBytes += Int64(size)
            }

            do {
                try fileManager.removeItem(at: itemURL)
            } catch {
                // If permission is denied or locked by a running process, continue safely
                continue
            }
        }

        return cleanedBytes
    }
}
