import Foundation

struct NativeScanResult {
    let categories: [CleanupCategory]
    let totalBytes: Int64
    let totalItems: Int
}

final class NativeCleanerService: @unchecked Sendable {
    private let fileManager = FileManager.default

    struct TargetSpec {
        let id: String
        let name: String
        let detail: String
        let relativePath: String
        let icon: String
        let excludedSubpaths: Set<String>

        init(id: String, name: String, detail: String, relativePath: String, icon: String, excludedSubpaths: Set<String> = []) {
            self.id = id
            self.name = name
            self.detail = detail
            self.relativePath = relativePath
            self.icon = icon
            self.excludedSubpaths = excludedSubpaths
        }
    }

    private let targets: [TargetSpec] = [
        TargetSpec(
            id: "xcode-data",
            name: "Xcode Derived Data",
            detail: "Rebuildable intermediate build products & symbol indexes",
            relativePath: "Library/Developer/Xcode/DerivedData",
            icon: "hammer"
        ),
        TargetSpec(
            id: "safari-cache",
            name: "Safari Cache",
            detail: "Rebuildable web browsing cache and site media",
            relativePath: "Library/Caches/com.apple.Safari",
            icon: "safari"
        ),
        TargetSpec(
            id: "chrome-cache",
            name: "Google Chrome Cache",
            detail: "Rebuildable Google Chrome HTTP disk cache",
            relativePath: "Library/Caches/Google/Chrome",
            icon: "globe"
        ),
        TargetSpec(
            id: "firefox-cache",
            name: "Firefox Cache",
            detail: "Rebuildable Mozilla Firefox web cache",
            relativePath: "Library/Caches/org.mozilla.firefox",
            icon: "flame"
        ),
        TargetSpec(
            id: "npm-cache",
            name: "npm & Node Cache",
            detail: "Cached Node package manager archives and tarballs",
            relativePath: ".npm",
            icon: "chevron.left.forwardslash.chevron.right"
        ),
        TargetSpec(
            id: "logs",
            name: "User App Logs",
            detail: "Stale crash logs and application diagnostics",
            relativePath: "Library/Logs",
            icon: "doc.text"
        ),
        TargetSpec(
            id: "application-cache",
            name: "Other App Caches",
            detail: "Temporary cache files generated by installed apps",
            relativePath: "Library/Caches",
            icon: "shippingbox",
            excludedSubpaths: ["com.apple.Safari", "Google", "org.mozilla.firefox", "com.apple.appstore"]
        )
    ]

    private func resolveURL(for relativePath: String) -> URL {
        FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(relativePath)
    }

    /// Calculate the real size and file count of a directory
    func calculateDirectoryMetrics(at url: URL, excluding: Set<String> = []) -> (bytes: Int64, count: Int) {
        var isDir: ObjCBool = false
        guard fileManager.fileExists(atPath: url.path, isDirectory: &isDir) else {
            return (0, 0)
        }

        if !isDir.boolValue {
            let size = Int64((try? url.resourceValues(forKeys: [.fileSizeKey]))?.fileSize ?? 0)
            return (size, 1)
        }

        var totalBytes: Int64 = 0
        var totalCount: Int = 0

        guard let enumerator = fileManager.enumerator(
            at: url,
            includingPropertiesForKeys: [.fileSizeKey, .isDirectoryKey, .isRegularFileKey],
            options: [.skipsPackageDescendants]
        ) else {
            return (0, 0)
        }

        for case let fileURL as URL in enumerator {
            // Check exclusions relative to parent directory
            if !excluding.isEmpty {
                let relative = fileURL.path.replacingOccurrences(of: url.path + "/", with: "")
                let topComponent = relative.split(separator: "/").first.map(String.init) ?? ""
                if excluding.contains(topComponent) {
                    enumerator.skipDescendants()
                    continue
                }
            }

            guard let resourceValues = try? fileURL.resourceValues(forKeys: [.fileSizeKey, .isRegularFileKey]) else {
                continue
            }
            if resourceValues.isRegularFile == true {
                totalBytes += Int64(resourceValues.fileSize ?? 0)
                totalCount += 1
            }
        }

        return (totalBytes, totalCount)
    }

    /// Scan all known targets and return populated categories with real disk sizes
    func scanAllTargets(onProgress: @escaping (String, String) -> Void) async -> NativeScanResult {
        var categories: [CleanupCategory] = []
        var totalBytes: Int64 = 0
        var totalItems: Int = 0

        for target in targets {
            let url = resolveURL(for: target.relativePath)
            let displayPath = "~/" + target.relativePath
            onProgress(target.name, displayPath)

            let (bytes, count) = calculateDirectoryMetrics(at: url, excluding: target.excludedSubpaths)

            let formattedCount = count > 0 ? NumberFormatter.localizedString(from: NSNumber(value: count), number: .decimal) : "0"

            let category = CleanupCategory(
                id: target.id,
                name: target.name,
                detail: target.detail,
                path: displayPath,
                items: formattedCount,
                sizeBytes: bytes,
                icon: target.icon,
                isSelected: bytes > 0
            )

            categories.append(category)
            totalBytes += bytes
            totalItems += count
        }

        return NativeScanResult(categories: categories, totalBytes: totalBytes, totalItems: totalItems)
    }

    /// Safely cleans contents inside a target directory without deleting the parent folder itself
    func cleanCategory(_ category: CleanupCategory, onProgress: @escaping (String) -> Void) async -> Int64 {
        guard let spec = targets.first(where: { $0.id == category.id }) else { return 0 }
        let url = resolveURL(for: spec.relativePath)

        var isDir: ObjCBool = false
        guard fileManager.fileExists(atPath: url.path, isDirectory: &isDir), isDir.boolValue else {
            return 0
        }

        guard let contents = try? fileManager.contentsOfDirectory(
            at: url,
            includingPropertiesForKeys: [.fileSizeKey],
            options: []
        ) else {
            return 0
        }

        var cleanedBytes: Int64 = 0

        for itemURL in contents {
            let itemName = itemURL.lastPathComponent
            // Skip hidden system files and any excluded subpaths
            if itemName.hasPrefix(".") && itemName != ".npm" { continue }
            if spec.excludedSubpaths.contains(itemName) { continue }

            onProgress("Removing \(category.name) · \(itemName)")

            // Calculate actual recursive size before deletion
            let (itemBytes, _) = calculateDirectoryMetrics(at: itemURL)

            do {
                try fileManager.removeItem(at: itemURL)
                cleanedBytes += itemBytes
            } catch {
                // If permission is denied or file is locked by a running process, continue safely
                continue
            }
        }

        return cleanedBytes
    }
}
